//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cv
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Class10 { get; set; }
        public string Stream { get; set; }
        public Nullable<int> Class12 { get; set; }
        public string Achivements { get; set; }
        public string Skills { get; set; }
        public string Interests { get; set; }
    }
}
