//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLancer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersEntities2 : DbContext
    {
        public UsersEntities2()
            : base("name=UsersEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cv> cvs { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<logindata> logindatas { get; set; }
        public virtual DbSet<signup> signups { get; set; }
    }
}
